name: Web App CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install system dependencies for PyAudio
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r web-app/requirements.txt
      - name: Test with pytest
        run: |
          pytest web-app/test_app.py
